// poke-holo.simey.me 가 쓰는 카드 88장. 사이트의 cards.json + CardProxy.svelte 의
// rarity 정규화 로직을 그대로 재현해 생성했다. 손으로 고치지 말 것.
//  · img         카드 앞면 (images.pokemontcg.io)
//  · mask/foil   카드별 포일 마스크 (poke-holo.b-cdn.net)
//  · effect      적용할 홀로 효과 키

export type EffectKey =
  | 'amazing-rare'
  | 'basic'
  | 'cosmos-holo'
  | 'radiant-holo'
  | 'rainbow-alt'
  | 'rainbow-holo'
  | 'regular-holo'
  | 'reverse-holo'
  | 'secret-rare'
  | 'shiny-rare'
  | 'shiny-v'
  | 'shiny-vmax'
  | 'swsh-pikachu'
  | 'tg-v'
  | 'tg-vmax'
  | 'trainer-full-art'
  | 'trainer-gallery-holo'
  | 'trainer-gallery-secret-rare'
  | 'v-full-art'
  | 'v-max'
  | 'v-regular'
  | 'v-star'

export type HoloCard = {
  id: string; name: string; section: string; sectionLabel: string
  rarity: string; subtypes: string[]; types: string[]; supertype: string
  effect: EffectKey
  img: string; mask: string; foil: string
}

export const CARDS: HoloCard[] = [
  {
    id: "swsh12pt5-160", name: "Pikachu",
    section: "showcase", sectionLabel: "\uc1fc\ucf00\uc774\uc2a4",
    rarity: "Rare Secret", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "swsh-pikachu",
    img: "https://images.pokemontcg.io/swsh12pt5/160_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12pt5/masks/upscaled/160_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12pt5/foils/upscaled/160_foil_etched_swsecret_2x.webp",
  },
  {
    id: "sm10-33", name: "Squirtle",
    section: "basics", sectionLabel: "\ucee4\uba3c",
    rarity: "Common", subtypes: ["Basic"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "basic",
    img: "https://images.pokemontcg.io/sm10/33_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/sm10/masks/upscaled/033_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/sm10/foils/upscaled/033_foil_holo_reverse_2x.webp",
  },
  {
    id: "sm115-7", name: "Charmander",
    section: "basics", sectionLabel: "\ucee4\uba3c",
    rarity: "Common", subtypes: ["Basic"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "basic",
    img: "https://images.pokemontcg.io/sm115/7_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/sm115/masks/upscaled/007_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/sm115/foils/upscaled/007_foil_holo_reverse_2x.webp",
  },
  {
    id: "sm35-1", name: "Bulbasaur",
    section: "basics", sectionLabel: "\ucee4\uba3c",
    rarity: "Common", subtypes: ["Basic"],
    types: ["Grass"], supertype: "Pok\u00e9mon",
    effect: "basic",
    img: "https://images.pokemontcg.io/sm35/1_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/sm35/masks/upscaled/001_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/sm35/foils/upscaled/001_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh12-127", name: "Togedemaru",
    section: "reverse", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c",
    rarity: "Common Reverse Holo", subtypes: ["Basic"],
    types: ["Metal"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh12/127_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/127_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/127_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh12-85", name: "Dedenne",
    section: "reverse", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c",
    rarity: "Uncommon Reverse Holo", subtypes: ["Basic"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh12/85_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/085_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/085_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh12-116", name: "Morpeko",
    section: "reverse", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c",
    rarity: "Uncommon Reverse Holo", subtypes: ["Basic"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh12/116_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/116_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/116_foil_holo_reverse_2x.webp",
  },
  {
    id: "pgo-24", name: "Articuno",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Basic"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/pgo/24_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/024_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/024_foil_holo_swholo_2x.webp",
  },
  {
    id: "pgo-29", name: "Zapdos",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/pgo/29_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/029_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/029_foil_holo_swholo_2x.webp",
  },
  {
    id: "pgo-12", name: "Moltres",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Basic"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/pgo/12_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/012_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/012_foil_holo_swholo_2x.webp",
  },
  {
    id: "swsh1-85", name: "Gengar",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Stage 2"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/swsh1/85_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh1/masks/upscaled/085_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh1/foils/upscaled/085_foil_holo_swholo_2x.webp",
  },
  {
    id: "swsh9-132", name: "Boss's Orders",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/swsh9/132_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/132_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/132_foil_holo_swholo_2x.webp",
  },
  {
    id: "pgo-43", name: "Tyranitar",
    section: "holos", sectionLabel: "\uc77c\ubc18 \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Stage 2"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "regular-holo",
    img: "https://images.pokemontcg.io/pgo/43_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/043_foil_holo_swholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/043_foil_holo_swholo_2x.webp",
  },
  {
    id: "swshp-SWSH012", name: "Morpeko",
    section: "cosmos", sectionLabel: "\ucf54\uc2a4\ubaa8\uc2a4",
    rarity: "Rare Holo Cosmos", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "cosmos-holo",
    img: "https://images.pokemontcg.io/swshp/SWSH012_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/012_foil_holo_cosmos_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/012_foil_holo_cosmos_2x.webp",
  },
  {
    id: "swsh45-60", name: "Professor's Research",
    section: "cosmos", sectionLabel: "\ucf54\uc2a4\ubaa8\uc2a4",
    rarity: "Rare Holo Cosmos", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "cosmos-holo",
    img: "https://images.pokemontcg.io/swsh45/60_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/060_foil_holo_cosmos_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/060_foil_holo_cosmos_2x.webp",
  },
  {
    id: "swshp-SWSH127", name: "Eevee",
    section: "cosmos", sectionLabel: "\ucf54\uc2a4\ubaa8\uc2a4",
    rarity: "Rare Holo Cosmos", subtypes: ["Basic"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "cosmos-holo",
    img: "https://images.pokemontcg.io/swshp/SWSH127_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/127_foil_holo_cosmos_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/127_foil_holo_cosmos_2x.webp",
  },
  {
    id: "pgo-11", name: "Radiant Charizard",
    section: "radiant", sectionLabel: "\ub798\ub514\uc5b8\ud2b8",
    rarity: "Radiant Rare", subtypes: ["Basic", "Radiant"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "radiant-holo",
    img: "https://images.pokemontcg.io/pgo/11_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/011_foil_etched_radiantholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/011_foil_etched_radiantholo_2x.webp",
  },
  {
    id: "swsh12-59", name: "Radiant Alakazam",
    section: "radiant", sectionLabel: "\ub798\ub514\uc5b8\ud2b8",
    rarity: "Radiant Rare", subtypes: ["Basic", "Radiant"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "radiant-holo",
    img: "https://images.pokemontcg.io/swsh12/59_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/059_foil_etched_radiantholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/059_foil_etched_radiantholo_2x.webp",
  },
  {
    id: "swsh12-120", name: "Radiant Jirachi",
    section: "radiant", sectionLabel: "\ub798\ub514\uc5b8\ud2b8",
    rarity: "Radiant Rare", subtypes: ["Basic", "Radiant"],
    types: ["Metal"], supertype: "Pok\u00e9mon",
    effect: "radiant-holo",
    img: "https://images.pokemontcg.io/swsh12/120_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/120_foil_etched_radiantholo_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/120_foil_etched_radiantholo_2x.webp",
  },
  {
    id: "swsh11tg-TG03", name: "Charizard",
    section: "basicGallery", sectionLabel: "\uac24\ub7ec\ub9ac \ud640\ub85c",
    rarity: "trainer gallery rare holo", subtypes: ["Stage 2"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "trainer-gallery-holo",
    img: "https://images.pokemontcg.io/swsh11tg/TG03_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg03_foil_holo_rainbow_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg03_foil_holo_rainbow_2x.webp",
  },
  {
    id: "swsh11tg-TG05", name: "Pikachu",
    section: "basicGallery", sectionLabel: "\uac24\ub7ec\ub9ac \ud640\ub85c",
    rarity: "trainer gallery rare holo", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "trainer-gallery-holo",
    img: "https://images.pokemontcg.io/swsh11tg/TG05_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg05_foil_holo_rainbow_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg05_foil_holo_rainbow_2x.webp",
  },
  {
    id: "swsh12tg-TG02", name: "Milotic",
    section: "basicGallery", sectionLabel: "\uac24\ub7ec\ub9ac \ud640\ub85c",
    rarity: "Rare Holo", subtypes: ["Stage 1"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "trainer-gallery-holo",
    img: "https://images.pokemontcg.io/swsh12tg/TG02_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/tg02_foil_holo_rainbow_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/tg02_foil_holo_rainbow_2x.webp",
  },
  {
    id: "swsh7-110", name: "Rayquaza V",
    section: "vee", sectionLabel: "V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V", "Rapid Strike"],
    types: ["Dragon"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/swsh7/110_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh7/masks/upscaled/110_foil_holo_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh7/foils/upscaled/110_foil_holo_sunpillar_2x.webp",
  },
  {
    id: "swsh12-138", name: "Lugia V",
    section: "vee", sectionLabel: "V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/swsh12/138_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/138_foil_holo_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/138_foil_holo_sunpillar_2x.webp",
  },
  {
    id: "pgo-49", name: "Dragonite V",
    section: "vee", sectionLabel: "V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V"],
    types: ["Dragon"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/pgo/49_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/049_foil_holo_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/049_foil_holo_sunpillar_2x.webp",
  },
  {
    id: "swsh8-250", name: "Mew V",
    section: "veeUltra", sectionLabel: "V \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V", "Fusion Strike"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh8/250_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/250_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/250_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh3-183", name: "Scizor V",
    section: "veeUltra", sectionLabel: "V \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V"],
    types: ["Metal"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh3/183_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh3/masks/upscaled/183_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh3/foils/upscaled/183_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh12-176", name: "Unown V",
    section: "veeUltra", sectionLabel: "V \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh12/176_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/176_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/176_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swshp-SWSH179", name: "Flareon V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Holo V", subtypes: ["Basic", "V", "Single Strike"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/swshp/SWSH179_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/179_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/179_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swshp-SWSH181", name: "Vaporeon V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Holo V", subtypes: ["Basic", "V", "Rapid Strike"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/swshp/SWSH181_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/181_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/181_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swshp-SWSH183", name: "Jolteon V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Holo V", subtypes: ["Basic", "V"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "v-regular",
    img: "https://images.pokemontcg.io/swshp/SWSH183_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/183_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/183_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh8-245", name: "Celebi V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V"],
    types: ["Grass"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh8/245_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/245_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/245_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh11-186", name: "Giratina V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V"],
    types: ["Dragon"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh11/186_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/186_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/186_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh10-177", name: "Origin Forme Dialga V",
    section: "veeAlt", sectionLabel: "V \uc5bc\ud130\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Basic", "V"],
    types: ["Metal"], supertype: "Pok\u00e9mon",
    effect: "v-full-art",
    img: "https://images.pokemontcg.io/swsh10/177_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh10/masks/upscaled/177_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh10/foils/upscaled/177_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh7-29", name: "Gyarados VMAX",
    section: "veeMax", sectionLabel: "VMAX",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "v-max",
    img: "https://images.pokemontcg.io/swsh7/29_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh7/masks/upscaled/029_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh7/foils/upscaled/029_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45-51", name: "Ditto VMAX",
    section: "veeMax", sectionLabel: "VMAX",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "v-max",
    img: "https://images.pokemontcg.io/swsh45/51_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/051_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/051_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9-29", name: "Kingler VMAX",
    section: "veeMax", sectionLabel: "VMAX",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "v-max",
    img: "https://images.pokemontcg.io/swsh9/29_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/029_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/029_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh8-270", name: "Espeon VMAX",
    section: "veeMaxAlt", sectionLabel: "VMAX \uc5bc\ud130",
    rarity: "Rare Rainbow Alt", subtypes: ["VMAX"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "rainbow-alt",
    img: "https://images.pokemontcg.io/swsh8/270_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/270_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/270_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh8-271", name: "Gengar VMAX",
    section: "veeMaxAlt", sectionLabel: "VMAX \uc5bc\ud130",
    rarity: "Rare Rainbow Alt", subtypes: ["VMAX", "Single Strike"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "rainbow-alt",
    img: "https://images.pokemontcg.io/swsh8/271_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/271_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/271_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh7-215", name: "Umbreon VMAX",
    section: "veeMaxAlt", sectionLabel: "VMAX \uc5bc\ud130",
    rarity: "Rare Rainbow Alt", subtypes: ["VMAX", "Single Strike"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "rainbow-alt",
    img: "https://images.pokemontcg.io/swsh7/215_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh7/masks/upscaled/215_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh7/foils/upscaled/215_foil_etched_swsecret_2x.webp",
  },
  {
    id: "pgo-31", name: "Mewtwo VSTAR",
    section: "veeStar", sectionLabel: "VSTAR",
    rarity: "Rare Holo VSTAR", subtypes: ["VSTAR"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "v-star",
    img: "https://images.pokemontcg.io/pgo/31_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/031_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/031_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swshp-SWSH214", name: "Lucario VSTAR",
    section: "veeStar", sectionLabel: "VSTAR",
    rarity: "Rare Holo VSTAR", subtypes: ["VSTAR"],
    types: ["Fighting"], supertype: "Pok\u00e9mon",
    effect: "v-star",
    img: "https://images.pokemontcg.io/swshp/SWSH214_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swshp/masks/upscaled/214_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swshp/foils/upscaled/214_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9-18", name: "Charizard VSTAR",
    section: "veeStar", sectionLabel: "VSTAR",
    rarity: "Rare Holo VSTAR", subtypes: ["VSTAR"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "v-star",
    img: "https://images.pokemontcg.io/swsh9/18_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/018_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/018_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh6-196", name: "Peonia",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh6/196_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh6/masks/upscaled/196_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh6/foils/upscaled/196_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9-167", name: "Barry",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh9/167_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/167_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/167_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh1-200", name: "Marnie",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh1/200_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh1/masks/upscaled/200_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh1/foils/upscaled/200_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh11tg-TG27", name: "Nessa",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh11tg/TG27_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg27_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg27_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh12tg-TG26", name: "Professor Burnet",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh12tg/TG26_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/tg26_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/tg26_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh11tg-TG26", name: "Kabu",
    section: "trainerHolo", sectionLabel: "\ud2b8\ub808\uc774\ub108 \ud480\uc544\ud2b8",
    rarity: "Rare Ultra", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "trainer-full-art",
    img: "https://images.pokemontcg.io/swsh11tg/TG26_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg26_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg26_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh4-188", name: "Pikachu VMAX",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["VMAX"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh4/188_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/188_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/188_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh12-197", name: "Alolan Vulpix VSTAR",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["VSTAR"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh12/197_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/197_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/197_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh10-204", name: "Irida",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh10/204_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh10/masks/upscaled/204_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh10/foils/upscaled/204_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh8-268", name: "Mew VMAX",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["VMAX", "Fusion Strike"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh8/268_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/268_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/268_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh9-175", name: "Whimsicott VSTAR",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["VSTAR"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh9/175_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/175_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/175_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh12-205", name: "Furisode Girl",
    section: "rainbow", sectionLabel: "\ub808\uc778\ubcf4\uc6b0",
    rarity: "Rare Rainbow", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "rainbow-holo",
    img: "https://images.pokemontcg.io/swsh12/205_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/205_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/205_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh2-209", name: "Twin Energy",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["Special"],
    types: [], supertype: "Energy",
    effect: "secret-rare",
    img: "https://images.pokemontcg.io/swsh2/209_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh2/masks/upscaled/209_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh2/foils/upscaled/209_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh9-186", name: "Ultra Ball",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["Item"],
    types: [], supertype: "Trainer",
    effect: "secret-rare",
    img: "https://images.pokemontcg.io/swsh9/186_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/186_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/186_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh10-213", name: "Path to the Peak",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["Stadium"],
    types: [], supertype: "Trainer",
    effect: "secret-rare",
    img: "https://images.pokemontcg.io/swsh10/213_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh10/masks/upscaled/213_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh10/foils/upscaled/213_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh8-280", name: "Flaaffy",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["Stage 1"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "secret-rare",
    img: "https://images.pokemontcg.io/swsh8/280_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/280_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/280_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh9-184", name: "Arceus VSTAR",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["VSTAR"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "secret-rare",
    img: "https://images.pokemontcg.io/swsh9/184_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/184_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/184_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh11tg-TG30", name: "Mew VMAX",
    section: "gold", sectionLabel: "\uace8\ub4dc \uc2dc\ud06c\ub9bf",
    rarity: "Rare Secret", subtypes: ["VMAX", "Fusion Strike"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "trainer-gallery-secret-rare",
    img: "https://images.pokemontcg.io/swsh11tg/TG30_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg30_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg30_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh9tg-TG16", name: "Mimikyu V",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "tg-v",
    img: "https://images.pokemontcg.io/swsh9tg/TG16_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/tg16_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/tg16_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9tg-TG18", name: "Single Strike Urshifu V",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V", "Single Strike"],
    types: ["Fighting"], supertype: "Pok\u00e9mon",
    effect: "tg-v",
    img: "https://images.pokemontcg.io/swsh9tg/TG18_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/tg18_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/tg18_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh11tg-TG16", name: "Pikachu V",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo V", subtypes: ["Basic", "V"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "tg-v",
    img: "https://images.pokemontcg.io/swsh11tg/TG16_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg16_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg16_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9tg-TG17", name: "Mimikyu VMAX",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "tg-vmax",
    img: "https://images.pokemontcg.io/swsh9tg/TG17_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/tg17_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/tg17_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9tg-TG19", name: "Single Strike Urshifu VMAX",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX", "Single Strike"],
    types: ["Fighting"], supertype: "Pok\u00e9mon",
    effect: "tg-vmax",
    img: "https://images.pokemontcg.io/swsh9tg/TG19_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/tg19_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/tg19_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh11tg-TG17", name: "Pikachu VMAX",
    section: "veeGallery", sectionLabel: "\uac24\ub7ec\ub9ac V",
    rarity: "Rare Holo VMAX", subtypes: ["VMAX"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "tg-vmax",
    img: "https://images.pokemontcg.io/swsh11tg/TG17_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh11/masks/upscaled/tg17_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh11/foils/upscaled/tg17_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh9-120", name: "Bidoof",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Common Reverse Holo", subtypes: ["Basic"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh9/120_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/120_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/120_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh12-49", name: "Pikachu",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Common Reverse Holo", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh12/49_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh12/masks/upscaled/049_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh12/foils/upscaled/049_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh8-138", name: "Onix",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Common Reverse Holo", subtypes: ["Basic"],
    types: ["Fighting"], supertype: "Pok\u00e9mon",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh8/138_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh8/masks/upscaled/138_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh8/foils/upscaled/138_foil_holo_reverse_2x.webp",
  },
  {
    id: "pgo-69", name: "Pok\u00e9Stop",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Uncommon Reverse Holo", subtypes: ["Stadium"],
    types: [], supertype: "Trainer",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/pgo/68_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/pgo/masks/upscaled/068_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/pgo/foils/upscaled/068_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh1-173", name: "Pok\u00e9 Kid",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Uncommon Reverse Holo", subtypes: ["Supporter"],
    types: [], supertype: "Trainer",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh1/173_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh1/masks/upscaled/173_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh1/foils/upscaled/173_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh9-150", name: "Ultra Ball",
    section: "reverse2", sectionLabel: "\ub9ac\ubc84\uc2a4 \ud640\ub85c 2",
    rarity: "Uncommon Reverse Holo", subtypes: ["Item"],
    types: [], supertype: "Trainer",
    effect: "reverse-holo",
    img: "https://images.pokemontcg.io/swsh9/150_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh9/masks/upscaled/150_foil_holo_reverse_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh9/foils/upscaled/150_foil_holo_reverse_2x.webp",
  },
  {
    id: "swsh4-9", name: "Celebi",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Grass"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/9_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/009_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/009_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh4-50", name: "Raikou",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Lightning"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/50_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/050_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/050_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh4-82", name: "Zacian",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Psychic"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/82_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/082_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/082_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh4-102", name: "Zamazenta",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Fighting"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/102_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/102_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/102_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh4-119", name: "Jirachi",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Metal"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/119_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/119_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/119_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh4-138", name: "Rayquaza",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh4/138_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh4/masks/upscaled/138_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh4/foils/upscaled/138_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh45-17", name: "Reshiram",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh45/17_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/017_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/017_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh45-21", name: "Kyogre",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh45/21_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/021_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/021_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh45-46", name: "Yveltal",
    section: "amazings", sectionLabel: "\uc5b4\uba54\uc774\uc9d5",
    rarity: "Amazing Rare", subtypes: ["Basic"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "amazing-rare",
    img: "https://images.pokemontcg.io/swsh45/46_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/046_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/046_foil_etched_swsecret_2x.webp",
  },
  {
    id: "swsh45sv-SV093", name: "Minccino",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny", subtypes: ["Basic"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "shiny-rare",
    img: "https://images.pokemontcg.io/swsh45sv/SV093_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv093_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv093_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45sv-SV094", name: "Cinccino",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny", subtypes: ["Stage 1"],
    types: ["Colorless"], supertype: "Pok\u00e9mon",
    effect: "shiny-rare",
    img: "https://images.pokemontcg.io/swsh45sv/SV094_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv094_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv094_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45sv-SV110", name: "Lapras V",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny V", subtypes: ["Basic", "V"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "shiny-v",
    img: "https://images.pokemontcg.io/swsh45sv/SV110_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv110_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv110_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45sv-SV023", name: "Galarian Darumaka",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny", subtypes: ["Basic"],
    types: ["Water"], supertype: "Pok\u00e9mon",
    effect: "shiny-rare",
    img: "https://images.pokemontcg.io/swsh45sv/SV023_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv023_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv023_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45sv-SV076", name: "Koffing",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny", subtypes: ["Basic"],
    types: ["Darkness"], supertype: "Pok\u00e9mon",
    effect: "shiny-rare",
    img: "https://images.pokemontcg.io/swsh45sv/SV076_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv076_foil_etched_sunpillar_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv076_foil_etched_sunpillar_2x.webp",
  },
  {
    id: "swsh45sv-SV107", name: "Charizard VMAX",
    section: "shinyVault", sectionLabel: "\uc0e4\uc774\ub2c8 \ubcfc\ud2b8",
    rarity: "Rare Shiny VMAX", subtypes: ["VMAX"],
    types: ["Fire"], supertype: "Pok\u00e9mon",
    effect: "shiny-vmax",
    img: "https://images.pokemontcg.io/swsh45sv/SV107_hires.png",
    mask: "https://poke-holo.b-cdn.net/foils/swsh45/masks/upscaled/sv107_foil_etched_swsecret_2x.webp",
    foil: "https://poke-holo.b-cdn.net/foils/swsh45/foils/upscaled/sv107_foil_etched_swsecret_2x.webp",
  },
]
